# Generated by Django 5.1.4 on 2025-06-04 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrationInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('pc_count', models.PositiveIntegerField()),
            ],
        ),
    ]
