# Generated by Django 5.1.4 on 2025-06-04 10:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('dise_code', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('school_name', models.CharField(max_length=100)),
                ('cluster', models.CharField(max_length=100)),
                ('village', models.CharField(max_length=100)),
                ('block', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('pincode', models.CharField(max_length=10)),
                ('principleName', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lab', models.CharField(max_length=100)),
                ('pc', models.IntegerField()),
                ('serial_number', models.CharField(max_length=100)),
                ('tft', models.CharField(max_length=100)),
                ('headphone', models.CharField(max_length=100)),
                ('webcam', models.CharField(max_length=100)),
                ('switch', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('dise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitor.school')),
            ],
        ),
    ]
