# Generated by Django 5.1.4 on 2025-06-16 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0002_school_asset'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='status',
            field=models.CharField(default='unactivated', max_length=20),
        ),
    ]
